- name: configure webserver
  hosts: all
  tasks:
  - name: install package
    yum:
     name: httpd
     state: present
  - name: create index.html file
    copy:
     content: "HELLO ANSIBLE JENKINS"
     dest: /var/www/html/index.html
  - name: restart service
    service:
     name: httpd
     state: restarted
     enabled: true
